# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fb5c1ac348bdf9c89e4634926c61fc9599e0c3546664df6ceacf5892325c3436e87b8e0b1fcb84c46f4dba761a05c6989b3a678a08bf445bbc1ebd8a1827d36

test:
  secret_key_base: cdab197388040de1826921e374d5af17fddad5e66fe605947bc83b4f18a0d9e60e1578a0542801cc8e92f1d150c2cdbe616e6d5ce735901ab905d6b0a1e7064b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
